name: SamplingBias
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10.14
  - pip:
    - numpy~=1.26.4
    - rpy2~=3.5.16
    - tensorflow~=2.15.1
    - tensorflow-probability~=0.23.0
    - bayesflow~=1.1.6
    - pandas~=2.2.2
    - matplotlib~=3.9.0
    - scipy~=1.12.0
    - tarp~=0.1.1
    - tqdm~=4.66.4
    - jupyter~=1.0.0
